### ISSUE TITLE
API Version?

### ISSUE THREAD

**Issue by erichhorde** [jzornow/intacct-ruby#6]
I'm looking, for example, at the resulting code for creating a customer and seeing some significant discrepancies from the XML specified in API documentation for [Creating Customers](https://developer.intacct.com/api/accounts-receivable/customers/#create-customer).  Is the gem targeted at a (possibly older) version of the Inacct API. 

Any assistance you could provide would be greatly appreciated.

**Comment by danielpowell4** [comment]
@erichhorde

When we create a customer, the call looks something like:

```rb
def activate
  request = Request.new(AUTHENTICATION_ATTRIBUTES)
  request.create :customer, customer_attrs
  send_request request
end

private

def customer_attrs
  {
    customerid: @client.id,
    name:       @client.name,
    status:     customer_status,
    custrepid:  @client.managing_director_id,
    displaycontact: {
      printas:    @client.name,
      first_name: @client.first_name,
      last_name:  @client.last_name,
      email1:     @client.email
    }
  }
end

def customer_status
  'active'
end
```

Where AUTHENTICATION_ATTRIBUTES and send request both live in a base gateway and look like:

```rb
AUTHENTICATION_ATTRIBUTES = {
      companyid:       ENV['...'],
      userid:          ENV['...'],
      user_password:   ENV['...'],
      senderid:        ENV['...'],
      sender_password: ENV['...']
    }.freeze

def send_request(request)
  request.send
  rescue => error
    Honeybadger.notify error_with_function_context(error, request.functions)
end
```

------

This gem works with the current Intacct API version. It was written with the intention of the integrating with the old Intacct API, which was changed sometime around late spring/early summer 2017.
